name: Build and Upload ZIP Artifact

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version
        id: get_version
        run: echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV

      - name: Run the packager
        run: |
          /bin/bash build.sh
          # build.sh should create dist/plugin.video.angelstudios-${VERSION}.zip

      - name: Prepare gh-pages directory
        run: |
          mkdir -p gh-pages
          cp dist/plugin.video.angelstudios-${{ env.VERSION }}.zip gh-pages/
          # If you have an index.html, copy it too:
          # cp dist/index.html gh-pages/

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
          publish_branch: gh-pages