name: Build and Upload ZIP Artifact

on:
  push:
    branches:
      - main

jobs:
  trigger_build:
    runs-on: ubuntu-latest

    # Don't to anything yet.  This is a placeholder for the build job.

    # steps:
    #   - name: Trigger build on repository.kodi.reavey05.com
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     run: |
    #       curl -X POST \
    #         -H "Accept: application/vnd.github+json" \
    #         -H "Authorization: Bearer $GITHUB_TOKEN" \
    #         https://api.github.com/repos/brianpatrickreavey/repository.kodi.reavey05.com/dispatches \
    #         -d '{"event_type":"trigger-build","client_payload":{"branch":"${GITHUB_REF_NAME}"}}'